# Generated by Django 4.2.7 on 2023-12-10 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0002_client_user_mailing_user_alter_mailing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template_name', models.CharField(max_length=120, verbose_name='темплейт')),
                ('email_subject', models.CharField(max_length=300, verbose_name='тема письма')),
                ('email_body', models.TextField(verbose_name='текст письма')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель темплейта')),
            ],
            options={
                'verbose_name': 'наполнение письма',
                'verbose_name_plural': 'наполнения писем',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время рассылки')),
                ('periodic_time', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=100, verbose_name='периодичность')),
                ('is_enabled', models.CharField(choices=[('enabled', 'Включить'), ('disabled', 'Выключено')], max_length=50, verbose_name='Включить рассылку')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('idle', 'Ожидание')], default='idle', max_length=50, verbose_name='статус рассылки')),
                ('next_send_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата следующей отправки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscribtionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('is_success', models.BooleanField(default=True, verbose_name='успешно')),
                ('last_mail_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.emailsubscribtion', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
        migrations.RemoveField(
            model_name='mailinglog',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mailing',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=450, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель клиента'),
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.DeleteModel(
            name='MailingLog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='emailsubscribtion',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='emailsubscribtion',
            name='email_filling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.emailfilling', verbose_name='наполнение письма'),
        ),
        migrations.AddField(
            model_name='emailsubscribtion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель рассылки'),
        ),
    ]
